export const allowedConfig: string[] = [
    '|',
    '-',
    'bold',
    'italic',
    'underline',
    'strikethrough',
    'link',
    'textColor',
    'backgroundColor',
    'removeFormat',
    'undo',
    'redo',
    'superscript',
    'subscript',
    'insertOrderedList',
    'insertUnorderedList',
    // 'justifyFull',
    // 'justifyCenter',
    // 'justifyLeft',
    // 'justifyRight'
]